services:
  busalertbot:
    container_name: busalertbot
    image: ghcr.io/yuejunfeng0909/busalertbot:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      - busalertbot-data:/app/data

volumes:
  busalertbot-data:
